import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { GetStaticProps } from 'next'

const inter = Inter({ subsets: ['latin'] })
interface Props {
  users: User[];
}
export const getStaticProps: GetStaticProps<Props> = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/users');
  const users = await res.json() as User[];
  return {
    props:{
      users,
    }
  }
}

export default function Home({ users } : Props) {
  console.log(users);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul>
          {users.map((user:any) => (
            <li key= {user.id}>{user.name}</li>
          ))}
        </ul>
      </main>
    </>
  )
}
